### ISSUE TITLE
undefined symbol: _ZTIN7Iex_2_27BaseExcE

### ISSUE THREAD

**Issue by zkl99999** [jamesbowman/openexrpython#28]
`pip3 install openexr`
  Using cached https://files.pythonhosted.org/packages/7c/c4/76bf884f59d3137847edf8b93aaf40f6257d8315d0064e8b1a606ad80b1b/OpenEXR-1.3.2.tar.gz
Building wheels for collected packages: openexr
  Building wheel for openexr (setup.py) ... done
  Stored in directory: /home/zn/.cache/pip/wheels/41/06/9f/c7dc838815b0e7dfc7d7dc19cc3d677edb47594d8489adc62a
Successfully built openexr
Installing collected packages: openexr
Successfully installed openexr-1.3.2

`python`
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
`>>> import openexr`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openexr'
`>>> import OpenEXR`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/zn/anaconda3/envs/pvnet/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

my pc is ubuntu 16 64bit, python3.6

**Comment by xtsdylyx** [comment]
same problem. Have you solved it?

**Comment by minygd** [comment]
Me too. The solution is deadly needed!

**Comment by minygd** [comment]
I have fixed this. Just make sure uninstall every pkgs/pip downloads/conda downloads of OpenEXR.
And then use `pip --no-cache-dir install OpenEXR` instead to avoid download the former pkgs.

**Comment by humayun** [comment]
I didn't fixed my error. I uninstall previous OpenEXR and reinstall by running above command, but it didn't fixsed  my problem. 
Here is my screen 
![Screenshot from 2019-10-31 12-05-46](https://user-images.githubusercontent.com/742339/68144004-855ee500-fee7-11e9-8b88-6257d77ef71c.png)
:

**Comment by humayun** [comment]
I tried but it didn't fixed same error for me. Below is my screen shot:
![Screenshot from 2019-11-04 09-44-31](https://user-images.githubusercontent.com/742339/68144112-c8b95380-fee7-11e9-9fe1-a8ef8a65fef6.png)

**Comment by peper0** [comment]
@humayun did you uninstall it also from conda? (`conda remove openexr`)

**Comment by humayun** [comment]
Yes, I did uninstall it from Conda and PIP.

**Comment by WHSnyder** [comment]
On MacOS with the same python version I hit similar errors and everything worked when installing with this command: pip install git+https://github.com/jamesbowman/openexrpython.git

**Comment by norru** [comment]
@WHSnyder's workaroud works for me on Ubuntu 18.04 and Anaconda2019.10

**Comment by electronicliujiang** [comment]
> I tried but it didn't fixed same error for me. Below is my screen shot:
> ![Screenshot from 2019-11-04 09-44-31](https://user-images.githubusercontent.com/742339/68144112-c8b95380-fee7-11e9-9fe1-a8ef8a65fef6.png)

Have you solved this problem

**Comment by humayun** [comment]
It is working with Python 2.* on Ubuntu machine. 

pip install OpenEXR

**Comment by electronicliujiang** [comment]
> `pip3 install openexr`
> Using cached https://files.pythonhosted.org/packages/7c/c4/76bf884f59d3137847edf8b93aaf40f6257d8315d0064e8b1a606ad80b1b/OpenEXR-1.3.2.tar.gz
> Building wheels for collected packages: openexr
> Building wheel for openexr (setup.py) ... done
> Stored in directory: /home/zn/.cache/pip/wheels/41/06/9f/c7dc838815b0e7dfc7d7dc19cc3d677edb47594d8489adc62a
> Successfully built openexr
> Installing collected packages: openexr
> Successfully installed openexr-1.3.2
> 
> `python`
> Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> `>>> import openexr`
> Traceback (most recent call last):
> File "", line 1, in
> ModuleNotFoundError: No module named 'openexr'
> `>>> import OpenEXR`
> Traceback (most recent call last):
> File "", line 1, in
> ImportError: /home/zn/anaconda3/envs/pvnet/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE
> 
> my pc is ubuntu 16 64bit, python3.6
v


> `pip3 install openexr`
> Using cached https://files.pythonhosted.org/packages/7c/c4/76bf884f59d3137847edf8b93aaf40f6257d8315d0064e8b1a606ad80b1b/OpenEXR-1.3.2.tar.gz
> Building wheels for collected packages: openexr
> Building wheel for openexr (setup.py) ... done
> Stored in directory: /home/zn/.cache/pip/wheels/41/06/9f/c7dc838815b0e7dfc7d7dc19cc3d677edb47594d8489adc62a
> Successfully built openexr
> Installing collected packages: openexr
> Successfully installed openexr-1.3.2
> 
> `python`
> Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> `>>> import openexr`
> Traceback (most recent call last):
> File "", line 1, in
> ModuleNotFoundError: No module named 'openexr'
> `>>> import OpenEXR`
> Traceback (most recent call last):
> File "", line 1, in
> ImportError: /home/zn/anaconda3/envs/pvnet/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE
> 
> my pc is ubuntu 16 64bit, python3.6
Have you solved this problem

**Comment by Shreeyak** [comment]
I'm also getting this error. Not able to resolve it. Tried removing conda+pip packages and installing with:

```bash
pip install git+https://github.com/jamesbowman/openexrpython.git
```

I have openexr system package installed:
```
$ sudo apt-get install -y openexr
...
openexr is already the newest version (2.2.0-11.1ubuntu1.2).
```

**Comment by ClementLeBihan** [comment]
Same problem on ubuntu 20.04 ...

**Comment by bing-xu-graphics** [comment]
same problem here. -_-  Trapped here for two days.

**Comment by Zaverichintanoxolo** [comment]
Stuck with Ubuntu 18.04 and python3.6. Any solutions or workaround ? 
Or anyone has some pointers?

**Comment by tovacinni** [comment]
Also having this issue :/

**Comment by 8bignic8** [comment]
I solved it with:
pip uninstall openexr
than
conda uninstall openexr
than
sudo apt-get remove -y openexr
than
sudo apt-get install -y openexr
than
pip install git+https://github.com/jamesbowman/openexrpython.git

yep dont know what solved it...but it did

**Comment by matthieugendrin** [comment]
A bit late, but just in case some people have the very similar `undefined symbol: _ZTIN7Iex_2_37BaseExcE`:
I'm on ubuntu 20.04
`sudo apt-get install openexr` installs version `openexr_2.3.0-6ubuntu0.5_amd64.deb` which is not the most recent one.
Whereas conda installs `openexr-2.5.5`

Try:
```
$ pip uninstall openexr
$ conda install -c conda-forge openexr-python
```
(note that I did not apt uninstall, but conda finds the proper version I guess)

**Comment by sinAshish** [comment]
this works for me
> https://github.com/jamesbowman/openexrpython/issues/28#issuecomment-557212292

**Comment by saikrn112** [comment]
your [solution](https://github.com/jamesbowman/openexrpython/issues/28#issuecomment-1279014897) worked @matthieugendrin !

**Comment by meshula** [comment]
BTW, the community continued to develop the bindings, and the source is now in the OpenEXR repo itself, https://github.com/AcademySoftwareFoundation/openexr and on PyPi as https://pypi.org/project/OpenEXR/

**Comment by amoazeni75** [comment]
I tried this approach, and worked in my case:

1- downgrade the Python package to 3.7
2- [Ubuntu]: sudo apt install libopenexr-dev
3- pip install OpenEXR==1.3.8

**Comment by RomanVeretenov** [comment]
Faced this issue on jetson nano with jetpack 4.5.1 on importing cv2 in python. I fixed it with `sudo apt install libilmbase12 --reinstall`. I have found out that the package verions on the host and in the deb repo is the same while the so files differ by md5sum. This command changes the /usr/lib/aarch64-linux-gnu/libIex-2_2.so.12 file (replaces the local file with the file from the repo) and the linkage error disappears

**Comment by meshula** [comment]
fwiw, OpenEXR now has officially supported and always up to date OpenEXR bindings on PyPi as I mentioned earlier in the thread. I notice you are trying to link against ilmbase, which means you probably have reasons to stick with the older bindings, so please ignore if you wish :)

https://pypi.org/project/OpenEXR/
